### ISSUE TITLE
How to display videos?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#105]
Crap, I never thought about how/where these are to be displayed on the student pages.

**Comment by webmasterkai** [comment]
Christophe Katrib would like the uploaded video to show up on the profile page. Any progress on this?

**Comment by webmasterkai** [comment]
As a quick fix I could show the video thumbnail as an image thumbnail and display the video instead of larger image...

**Comment by webmasterkai** [comment]
The how is perhaps done. Search for katrib Video thumbs are at the end of the list.
