### ISSUE TITLE
For some reason the program listing swaps the order of LeRoy Hoffberger School of Painting and Illustration Practice

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#106]
I guess its using the "h" from from hoffberger for that?
https://www.dropbox.com/s/ubslvxiu83dd14l/Screenshot%202015-01-21%2017.07.33.png?dl=0

**Comment by webmasterkai** [comment]
The order in the yaml file maybe?

**Comment by bjornmeansbear** [comment]
I'll check that.

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kb@ookb.co
w:   www.ookb.co
w:   www.cape.io
twitter: @bjornmeansbear

**Comment by bjornmeansbear** [comment]
you were correct sir.
