### ISSUE TITLE
Still need to work out the students displaying on the site vs. whether or not they show up in the new google doc

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#110]
Julia Marvel (jmarvel) for instance, should not show in this list:
https://www.dropbox.com/s/crme9lddk41gbik/Screenshot%202015-01-21%2022.02.34.png?dl=0

Nor have a page... http://www.micagradshow.com/students/jmarvel/

**Comment by webmasterkai** [comment]
404 bro.
