### ISSUE TITLE
Firefox profile pic overlay filter issue

### ISSUE THREAD

**Issue by alexjacque** [OOKB/grad-show-2015#111]
This is one of the problems my roommate reported. Something is not quite right with the complicated css filter property in Firefox. Seems to work just fine in Chrome and Safari. See gif below.

![Filter issue gif](https://dl.dropboxusercontent.com/u/32129742/temp/mgs_filter_issue.gif)

**Comment by bjornmeansbear** [comment]
Great! Thanks for this. Useful to have concrete "problem scenario" to solve.
