### ISSUE TITLE
Anyway to speed up the cache-refresh on imgix? Images stick around way to long after being deleted by students.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#113]
lcooper02 and epark02 have both fixed their bad images, and reordered what they have left, but the site still uses their out of date image orders and contents.

**Comment by webmasterkai** [comment]
We are lucky if the Imgix cache lasts a few hours. There is probably something else broken about those users.

**Comment by webmasterkai** [comment]
I just found and deleted 12 images in the database that had # in the filename... Files were likely removed from Cloudfiles directly and not through the EZLE api...
