### ISSUE TITLE
Figure out better implementation of the paper script

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#69]
Currently it uses a ton of processor to render the animation. Is there anyway to get it to stop animating when not on the screen? maybe it "kills" the animation to roll it out of view?

**Comment by bjornmeansbear** [comment]
@alexjacque do you know if there is anyway to tell a paper.js function to only run when/if on screen? currently the logo animation is running all the time and killing site performance

**Comment by alexjacque** [comment]
From what I see there's no startAnimation() stopAnimation() functions, but I can just set a window listener  (for scroll and resize) and toggle a boolean to run or skip the animation block. The stop/start part is working fine, just need to correctly get the bounds and offset of the canvas properly w/o jQuery.

**Comment by alexjacque** [comment]
Okay. So I got that all working, but I realized that the paper script onFrame(event) function is only being called when the canvas is within view, so it actually stops animating / pauses when off screen.

If you put a console.log("animating") line within that function you can see for yourself, or just look at your CPU usage when looking at the top of the page vs when looking at the bottom of the page.

**Comment by bjornmeansbear** [comment]
Thanks for investigating this…
