### ISSUE TITLE
Figure out why a handful of profile images are missing

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#89]
mruston (teaching)
cfredrick (community arts)
hsilverman01 (community arts)

and there are more...

**Comment by webmasterkai** [comment]
This is from long ago. There was a bug with the admin interface. We didn't see the bug for these images because they were cached at Imgix.

**Comment by bjornmeansbear** [comment]
So do I need them to re-upload profile pics?

**Comment by webmasterkai** [comment]
That is the easiest solution

**Comment by bjornmeansbear** [comment]
emailed students with missing profile pics and asked them to upload new ones.

**Comment by bjornmeansbear** [comment]
Already two fixed... good, that should do it.
