### ISSUE TITLE
Megan Liggett (mliggett) isn't showing up in the MAT listing

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#91]
Megan Liggett (mliggett) isn't showing up in the MAT listing (http://www.micagradshow.com/#students)
But she does have a student page.
http://www.micagradshow.com/students/mliggett/

She also claims that she has uploaded images, but they aren't showing...
What do I check?

**Comment by webmasterkai** [comment]
Confirmed she has a profile picture.

    r.db('mica').table('users').get('mliggett')('pic')

I just did a gulp deploy and she showed up...
