### ISSUE TITLE
Program listings on student pages seem to pull everyone from some old list

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#93]
Current listing of showing people is in the MGS website tab of this
https://docs.google.com/a/mica.edu/spreadsheets/d/1m0ah7DtyQ_benGdGA9w41a7_vkrBmJeRH8CNWXtvT6Q/edit#gid=0

We need to figure this out.

**Comment by webmasterkai** [comment]
If they are not in that list they should not show up? I've found six people in our db that are missing from that list ajain, cfisher, jchristenson, jmarvel, syoo01, skooper.

**Comment by bjornmeansbear** [comment]
Yes, that list should be used as the "check" as to whether they show up. Within that list they are now marking "True" if they are not showing on top of that.

**Comment by webmasterkai** [comment]
Future deploy will omit students that aren't found in the sheet.
