### ISSUE TITLE
Investigate speed issues on student gallery

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/grad-show-2015#97]
Seems really slow to load next/prev images? When other things are done, maybe look into this.

**Comment by webmasterkai** [comment]
It's the image resizing at imgix. React doesn't want to replace the image until it is fully loaded.

**Comment by bjornmeansbear** [comment]
Ah. okay. Maybe some sort of loading graphic might be useful then... If there is text, then that immediately updates while there is a lag in the image, so its slightly confusing. This is low priority, we'll work on it if we get everything else figured out :)

**Comment by bjornmeansbear** [comment]
I think this is solved now that we're doing things differently...
